name: EconomySystem
version: '1.0-SNAPSHOT'
main: de.imdacro.economySystem.EconomySystem
api-version: '1.21'
authors: [ ImDacro ]
softdepend:
  - Vault

commands:
  balance:
    description: Shows the balance of a player
    usage: /balance [player]
    permission: economysystem.command.balance
  pay:
    description: Pay a player
    usage: /pay <player> <amount>
    permission: economysystem.command.pay
  economyadmin:
    description: Economy admin commands
    usage: /economyadmin <set|add|remove> <player> <amount>
    permission: economysystem.command.economyadmin
  balancetop:
    description: Shows the top 10 players with the highest balance
    usage: /balancetop
    permission: economysystem.command.balancetop